### ISSUE TITLE
Using SQL query with REGEXP operator in Python throws an error

### ISSUE THREAD

**Issue by sushantsikka** [thomasnield/oreilly_advanced_sql_for_data#5]
I am trying to use a SQL query with REGEXP operator in Python and it is throwing an error.

Here is my code:
```
from sqlalchemy import create_engine, text

engine = create_engine('sqlite:///thunderbird_manufacturing.db')
conn = engine.connect()

def reg_exp():
    stmt = text("SELECT '$181.12' REGEXP '\$181\.12' --true")
    return list(conn.execute(stmt))

print(reg_exp())
```
This throws the following error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such function: REGEXP [SQL: "SELECT '$181.12' REGEXP '\\$181\\.12' --true"]
```
I tried the following query string `stmt = text("SELECT \'$181.12\' REGEXP \'\$181\.12\' --true")` but it throws the same error.

Can you help me correct the above code ?

**Comment by sushantsikka** [comment]
Does SQLAlchemy even support REGEXP operator ? 

I tried SQLite3 with the following code:

```
import sqlite3

conn = sqlite3.connect('thunderbird_manufacturing.db')
c = conn.cursor()

stmt = "SELECT \'TX\' REGEXP \'TX\'"

c.execute(stmt)

print(c.fetchall())
```
But that too returns the error "no such function: REGEXP".

**Comment by thomasnield** [comment]
Hi @sushantsikka, I forgot to highlight something in the regex section. The SQLite engine does not support a `REGEXP` implementation by default. SQLiteStudio puts in a REGEXP implementation but if you are using a programming platform you will need to provide an implementation as documented here: 

https://stackoverflow.com/a/8338515/1373258

For Python, you can actually implement it using a Python function at runtime.
 
https://stackoverflow.com/a/5365533/1373258

Does that help? I'll update the notes later today with this new piece of information, as well as a short section on recursive queries.

**Comment by sushantsikka** [comment]
@thomasnield Thanks !

I tried this code:

```
import sqlite3
import re

def regexp(expr, item):
    reg = re.compile(expr)
    return reg.search(item) is not None

conn = sqlite3.connect('thunderbird_manufacturing.db')
conn.create_function("REGEXP", 2, regexp)
cursor = conn.cursor()

stmt="SELECT * FROM CUSTOMER WHERE ADDRESS REGEXP \'.*(Blvd|St)$\'"
cursor.execute(stmt)

print(cursor.fetchall())
```
and it works fine.

**Comment by thomasnield** [comment]
Awesome, glad that helped and let me know if you need anything else.

**Comment by JesselyEnriquez** [comment]
Sorry I am curious so I used REGEXP prior to defining it in python and sqlite but then when I removed it from my py file every time I just attempted to use a "LIKE" within a sql statement I would get the same error. So I defined it in the python & sql module, now all my statements with "LIKE" work but I still cannot use REGEXP anywhere. 
 
Is this something I will continually have to do each time or is there something i missed?

**Comment by thomasnield** [comment]
@JesselyEnriquez I'm confused, so you remove the REGEXP implementation and then it breaks the LIKE operator?  

And yes, you need to have REGEXP implemented to the SQLite engine wherever it is called. Look at the REGEXP documentation on this page: https://www.sqlite.org/lang_expr.html

**Comment by thomasnield** [comment]
Going down this further, it looks like the REGEXP is an application-defined function: https://www.sqlite.org/appfunc.html

**Comment by JesselyEnriquez** [comment]
You are correct, when I removed the REGEXP from my SQL statement and it broke the LIKE operator. I deleted the file, tried to clear the sql history, restarted my computer not sure how to undo it. 
The only way I can use the LIKE operator now is if I define REGEXP and add the definition into the for python and sql, as [sushantsikka](https://github.com/sushantsikka) did above... without it I get the same error as earlier only now from my statments with the LIKE operator
